#!/bin/bash


function usage {
 echo ""
 echo "Usage: ${0##*/}  <working dir> <output bids dir> <subjids..>"
 echo "" 
 
}

if [ "$#" -lt 2 ]
then
 usage
 exit 1
fi

execpath=`dirname $0`
execpath=`realpath $execpath`

work_dir=$1
out_bids=$2

mkdir -p $out_bids
out_bids=`realpath $out_bids`

shift 2

source $parcellate_cfg


for subj in $@
do

track_dir=$work_dir/$subj/bedpost.${parcellation_name}/probtrack

t1w_subj=$work_dir/$subj/t1/t1.brain.inorm.nii.gz
dti_parc_subj=$track_dir/diffusion_parcellation.masked.nii.gz
dti_parc_subj_mni=$track_dir/$atlas/diffusion_parcellation.masked.nii.gz
dti_parc_subj_normmax=$track_dir/diffusion_parcellation.masked.normMax.nii.gz
dti_parc_subj_mni_normmax=$track_dir/$atlas/diffusion_parcellation.masked.normMax.nii.gz

paths_parc_subj_mni=$work_dir/$subj/bedpost.${parcellation_name}/probtrack_parcels_to_targets/$atlas/seg_paths.$atlas.nii.gz
paths_parc_subj=$work_dir/$subj/bedpost.${parcellation_name}/probtrack_parcels_to_targets/seg_paths.nii.gz

out_subj_dir=$out_bids/$subj/anat
mkdir -p $out_subj_dir

out_t1w=$out_subj_dir/${subj}_T1w.nii.gz
out_parc=$out_subj_dir/${subj}_space-T1w_${bids_tags}_norm-off_diffparc.nii.gz
out_parc_mni=$out_subj_dir/${subj}_reg-affine_space-${atlas}_${bids_tags}_norm-off_diffparc.nii.gz
out_parc_normmax=$out_subj_dir/${subj}_space-T1w_${bids_tags}_norm-max_diffparc.nii.gz
out_parc_mni_normmax=$out_subj_dir/${subj}_reg-affine_space-${atlas}_${bids_tags}_norm-max_diffparc.nii.gz

out_paths=$out_subj_dir/${subj}_space-T1w_${bids_tags}_pathsparc.nii.gz
out_paths_mni=$out_subj_dir/${subj}_reg-affine_space-${atlas}_${bids_tags}_pathsparc.nii.gz

ln -srfv $t1w_subj $out_t1w
ln -srfv $dti_parc_subj $out_parc
ln -srfv $dti_parc_subj_mni $out_parc_mni

ln -srfv $dti_parc_subj_normmax $out_parc_normmax
ln -srfv $dti_parc_subj_mni_normmax $out_parc_mni_normmax

ln -srfv $paths_parc_subj $out_paths
ln -srfv $paths_parc_subj_mni $out_paths_mni

done #subj

