#!/bin/bash


function usage {
 echo ""
 echo "Usage: ${0##*/}  <working dir> <output bids dir> <subjids..>"
 echo "" 
 
}

if [ "$#" -lt 2 ]
then
 usage
 exit 1
fi

execpath=`dirname $0`
execpath=`realpath $execpath`

work_dir=$1
out_bids=$2

mkdir -p $out_bids
out_bids=`realpath $out_bids`

shift 2

source $parcellate_cfg


for subj in $@
do


track_dir=$work_dir/$subj/bedpost.${parcellation_name}/probtrack
dti_parc_subj=$track_dir/diffusion_parcellation.masked.nii.gz
dti_parc_subj_mni=$track_dir/$atlas/diffusion_parcellation.masked.nii.gz

out_subj_dir=$out_bids/$subj/anat
mkdir -p $out_subj_dir

out_parc=$out_subj_dir/${subj}_space-T1w_${bids_tags}_diffparc.nii.gz
out_parc_mni=$out_subj_dir/${subj}_reg-affine_space-${atlas}_${bids_tags}_diffparc.nii.gz

cp -v $dti_parc_subj $out_parc
cp -v $dti_parc_subj_mni $out_parc_mni

done #subj

