#!/bin/bash


function usage {
 echo ""
 echo "Usage: ${0##*/}  <working dir> <output bids dir> <subjids..>"
 echo "" 
 
}

if [ "$#" -lt 2 ]
then
 usage
 exit 1
fi

execpath=`dirname $0`
execpath=`realpath $execpath`

work_dir=$1
out_bids=$2

mkdir -p $out_bids
out_bids=`realpath $out_bids`

shift 2

source $parcellate_cfg


for subj_sess_prefix in $@
do

#check if has session-level
subj=${subj_sess_prefix%%_ses*}
if [ "$subj" = "$subj_sess_prefix" ]
then
    #no session level
    subj_sess_dir=$subj
else
    sess=${subj_sess_prefix##*_}
    subj_sess_dir=$subj/$sess
fi

echo subj_sess_dir: $subj_sess_dir
echo subj_sess_prefix: $subj_sess_prefix
subj_dir=$work_dir/$subj_sess_prefix

track_dir=$work_dir/${subj_sess_prefix}/bedpost.${parcellation_name}/probtrack

t1w_subj=$work_dir/${subj_sess_prefix}/t1/t1.brain.inorm.nii.gz
dti_parc_subj=$track_dir/diffusion_parcellation.masked.nii.gz
dti_parc_subj_mni=$track_dir/$atlas/diffusion_parcellation.masked.nii.gz
dti_parc_subj_normmax=$track_dir/diffusion_parcellation.masked.normMax.nii.gz
dti_parc_subj_mni_normmax=$track_dir/$atlas/diffusion_parcellation.masked.normMax.nii.gz

dti_kmeans_subj=$track_dir/diffusion_parcellation.kmeans.nii.gz
dti_kmeans_subj_mni=$track_dir/$atlas/diffusion_parcellation.kmeans.nii.gz


paths_parc_subj_mni=$work_dir/${subj_sess_prefix}/bedpost.${parcellation_name}/probtrack_parcels_to_targets/$atlas/seg_paths.$atlas.nii.gz
paths_parc_subj=$work_dir/${subj_sess_prefix}/bedpost.${parcellation_name}/probtrack_parcels_to_targets/seg_paths.nii.gz

t1w_seed_seg=$work_dir/${subj_sess_prefix}/$seed_file
t1w_target_seg=$work_dir/${subj_sess_prefix}/$target_seg

out_subj_dir=$out_bids/${subj_sess_dir}/anat
mkdir -p $out_subj_dir

out_t1w=$out_subj_dir/${subj_sess_prefix}_T1w.nii.gz
out_parc=$out_subj_dir/${subj_sess_prefix}_space-T1w_${bids_tags}_norm-off_diffparc.nii.gz
out_parc_mni=$out_subj_dir/${subj_sess_prefix}_reg-affine_space-${atlas}_${bids_tags}_norm-off_diffparc.nii.gz

out_kmeans=$out_subj_dir/${subj_sess_prefix}_space-T1w_${bids_tags}_method-kmeans_diffparc.nii.gz
out_kmeans_mni=$out_subj_dir/${subj_sess_prefix}_reg-affine_space-${atlas}_${bids_tags}_method-kmeans_diffparc.nii.gz

out_parc_normmax=$out_subj_dir/${subj_sess_prefix}_space-T1w_${bids_tags}_norm-max_diffparc.nii.gz
out_parc_mni_normmax=$out_subj_dir/${subj_sess_prefix}_reg-affine_space-${atlas}_${bids_tags}_norm-max_diffparc.nii.gz

out_t1w_seed_seg=$out_subj_dir/${subj_sess_prefix}_space-T1w_${bids_tags}_inseed.nii.gz
out_t1w_target_seg=$out_subj_dir/${subj_sess_prefix}_space-T1w_${bids_tags}_intargets.nii.gz

out_paths=$out_subj_dir/${subj_sess_prefix}_space-T1w_${bids_tags}_pathsparc.nii.gz
out_paths_mni=$out_subj_dir/${subj_sess_prefix}_reg-affine_space-${atlas}_${bids_tags}_pathsparc.nii.gz

#add:  $work_dir/${subj_sess_prefix}/bedpost.${parcellation_name}/connMap.mat


connmap=$work_dir/${subj_sess_prefix}/bedpost.${parcellation_name}/connMap.mat
out_connmap=$out_subj_dir/${subj_sess_prefix}_space-T1w_res-${seed_res}_${bids_tags}_connMap.mat

if [  -e $connmap ]
then
ln -srfv $connmap $out_connmap
fi

if [  -e $t1w_subj ]
then
ln -srfv $t1w_subj $out_t1w
fi

if [ -e $t1w_seed_seg ]
then
ln -srfv $t1w_seed_seg $out_t1w_seed_seg
fi
if [ -e $t1w_target_seg ]
then
ln -srfv $t1w_target_seg $out_t1w_target_seg
fi
if [ -e $dti_parc_subj ]
then
ln -srfv $dti_parc_subj $out_parc
fi
if [ -e $dti_parc_subj_mni ]
then
ln -srfv $dti_parc_subj_mni $out_parc_mni
fi

if [ -e $dti_kmeans_subj ]
then
ln -srfv $dti_kmeans_subj $out_kmeans
fi
if [ -e $dti_kmeans_subj_mni ]
then
ln -srfv $dti_kmeans_subj_mni $out_kmeans_mni
fi

if [  -e $dti_parc_subj_normmax ]
then
ln -srfv $dti_parc_subj_normmax $out_parc_normmax
fi
if [  -e $dti_parc_subj_mni_normmax ]
then
ln -srfv $dti_parc_subj_mni_normmax $out_parc_mni_normmax
fi

if [  -e $paths_parc_subj ]
then
ln -srfv $paths_parc_subj $out_paths
fi

if [  -e $paths_parc_subj_mni ]
then
ln -srfv $paths_parc_subj_mni $out_paths_mni
fi
done #subj

