#!/bin/bash

version=v95

mcr_dir=`dirname $0`
matlab_dir=`realpath $mcr_dir/../matlab`
out_dir=$mcr_dir/$version

mkdir -p $out_dir

for m in `ls $matlab_dir/*.m`
do

filename=${m##*/}
funcname=${filename%.m}

echo "Compiling $filename ..."
mcc -v -N -I $matlab_dir -m -d $out_dir $filename 
echo "Removing extra files: $out_dir/*.{txt,sh,log}"
rm $out_dir/*.{txt,sh,log}

done
